"use strict";

//words arrays
var words = [
'Deprivation', 'Inmost', 'Incommunicated', 'Loving cup', 'A mornings', 'Buxeous', 'Pleurobranchia', 'Epanadiplosis', 'Stability', 'Verbarrosella',
'Inebriate', 'Pulverable', 'Braggadocio', 'Flag waver', 'Crofter', 'Equilateral','Communicator', 'Crud', 'Bewray', 'Anchorable', 'Sulphonate', 
'Harder', 'Merchandising', 'Arteriovenous', 'Birth'
];

//definitions array
var definition = [
'The act of depriving dispossessing or bereaving the act of deposing or divesting of some dignity',
'Deepest within farthest from the surface or external part innermost',
'Not communicated or imparted', ' A large ornamental drinking vessel having two or more handles intended to pass from hand to hand as at a banquet',
'In the morning every morning', 'Belonging to the box tree', 'Same as Pleurobranch',
'A figure by which the same word is used both at the beginning and at the end of a sentence as ldquoRejoice in the Lord always and again I say Rejoicerdquo',
'he state or quality of being stable or firm steadiness stableness firmness strength to stand without being moved or overthrown as the stability of a structure the stability of a throne or a constitution',
'A beautiful Australian parrakeet Platycercus eximius often kept as a cage bird The head and back of the neck are scarlet the throat is white the back dark green varied with lighter green and the breast yellow',
'To become drunk', 'Capable of being reduced to fine powder pulverizable', 'A braggart a boaster a swaggerer', 'an extreme bellicose nationalist',
'One who rents and tills a small farm or holding as the crofters of Scotland', 'Having all the sides equal as an equilateral triangle an equilateral polygon',
'One who communicates', 'See Curd', 'To soil See Beray', 'Fit for anchorage', 'A salt of sulphonic acid',
'A South African mullet salted for food', 'The activities associated with selling products such as identification of the market7 advertising at the right time in the right media7 and creating attractive packaging and displays also the study of the best methods to accomplish such goals',
'connecting an artery to a vein', 'The act or fact of coming into life or of being born generally applied to human beings as the birth of a son'
];
// the program is wrapped in a ready function
$(document).ready(function(){
	// this runs every 3 seconds
	setInterval(function() {
		 $("#word").clone().appendTo("body");
		var rando = Math.floor((Math.random() * 24) + 0); // rando create a random number between 0 and 24(this is bc there is 25 words/definitions)
		$('#word').text(words[rando] + ': ' + definition[rando]);//updates the <div> to display the words[random index generated by rando]
	}, 3000);
	
});